name: Integration

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.26.4'
          cache: true

      - name: Build
        env:
          CGO_ENABLED: 0
        run: |
          go build ./...

      - name: Run Tests
        run: |
          go test ./...

# هنا هعمل خطوة جديدة وهي اني اعمل تست  لملف الدوكر واعمل تست للايمج بتاعتوا 

  docker-test:
    runs-on: ubuntu-latest
    needs: [build]  #دي عشان اقولوا ان الخطوة دي محتاجة الخطوة اللي فوقها تخلص الاول 
    steps:
      - uses: actions/checkout@v6

      - name: Build Docker Image
        run: |
          docker build .

      - name: Run Docker Container
        run: |
          docker run --name myapp-container -d myapp:latest

      - name: Test Docker Container
        run: |
          docker exec myapp-container go test ./...

      - name: Stop and Remove Docker Container
        run: |
          docker stop myapp-container
          docker rm myapp-container