name: Integration

on: push

jobs:
  build:
    # runs-on: windows-latest      # هنعمل حاجه جديدة وهي ان اعمل تيست للجو اب علي اكتر من نظام تشغيل 
    # وهي ين استخدم ال matrix عشان اعمل تيست علي اكتر من نظام تشغيل   
    # وكمان اقدر اسنخدم اكتر من فيرجن للجو 
    strategy:
      matrix:
        os:
          - ubuntu-latest
          #- windows-latest
          # - macos-latest
        go_version: 
          - 1.26.4 
            # هنا هعمل تيست علي اكتر من فيرجن للجو
            # الايرور اللي بيطلع بسسب ان الباكديج بتاعت الفيرجن مش موجودة    
        arch:  # دي اللي هتخلي السيستم يشتغل علي اكتر من معمارية
          - amd64
          - arm64

    
    runs_on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: ${{ matrix.go_version }}
          cache: true

      - name: Build
        env:
          CGO_ENABLED: 0
          go_version: ${{ matrix.go_version }}
          GOARCH: ${{ matrix.arch }}
        run: |
          go build -o myproject
          echo "Build completed successfully."

      - name: Run Tests
        run: |
          go test ./...
      - name : Integration Test                 # هنا هعمل خطوة جديدة وهي اني اعمل تست  لملف الدوكر واعمل تست للايمج بتاعتوا 
        #shell: bash   # دي لو انا شغال علي الوبندوز فبقولوا
        run: |
          ./myproject 
          res=$(curl localhost:3000)  
          [[$res == "Hello, World!"]]  
        #عشان اعمل تيست علي الريسبونس اللي بيجي من السيرفر بتاعي

  docker-test:
    runs-on: ubuntu-latest 
    needs: [build]  #دي عشان اقولوا ان الخطوة دي محتاجة الخطوة اللي فوقها تخلص الاول 
    steps:
      - uses: actions/checkout@v6

      - name: Build Docker Image
        run: |
          docker build .

      # - name: Run Docker Container
      #   run: |
      #     docker run --name myapp-container -d myapp:latest

      # - name: Test Docker Container
      #   run: |
      #     docker exec myapp-container go test ./...

      # - name: Stop and Remove Docker Container
      #   run: |
      #     docker stop myapp-container
      #     docker rm myapp-container
